//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{


    public partial class frm_DepartmantData
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        
        
        protected global::System.Web.UI.WebControls.TextBox TextBox1;
        protected global::System.Web.UI.WebControls.TextBox TextBox2;
       
        protected global::System.Web.UI.WebControls.Button Button4;
        protected global::System.Web.UI.WebControls.Button Button3;


        protected global::System.Web.UI.WebControls.GridView GridView1;

        protected global::System.Web.UI.WebControls.DropDownList DropDownList1;
       
        protected global::System.Web.UI.WebControls.Label Label5;
        protected global::System.Web.UI.WebControls.Label Label2;
        protected global::System.Web.UI.WebControls.Label Label3;
        protected global::System.Web.UI.WebControls.Label Label4;


        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource2;
    }
}
